config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root to: 'homes#top'

  post 'books/book_search' => 'books#search', as: 'book_search'
  post 'users/user_search' => 'users#search', as: 'user_search'
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'home/about' => 'homes#about' , as: 'about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search(word)
    @result_title = self.where("title LIKE?", "%#{word}")
    @result_body = self.where("body LIKE?", "%#{word}")
    @books = @result_title + @result_body
    return @books
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # association関連の記述
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # follow関連のassociationの記述
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # active_storageを使った画像の設定
  has_one_attached :profile_image

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user_id)
    followings.include?(user_id)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search(word)
    @result_name = self.where("name LIKE?", "%#{word}")
    @result_introduction = self.where("introduction LIKE?", "%#{word}")
    @users = @result_name + @result_introduction
    return @users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user, only: [:edit]

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.new
    @book_one = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book_one = Book.find(params[:id])
  end

  def update
    @book_one = Book.find(params[:id])
    if @book_one.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book_one)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def search
    @books = Book.search(params[:word])
    @book = Book.new
    if @books.count != 0
      render :index
    else
      flash[:notice] = "検索対象にヒットしたものはありませんでした。"
      redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def check_user
    @book = Book.find(params[:id])
      unless @book.user == current_user
        redirect_to books_path
      end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    if favorite.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

  def create 
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user, only: [:edit]

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def search
    @users = User.search(params[:user_search])
    if @users.count != 0
      render :index
    else
      flash[:notice] = "検索対象にヒットしたものはありませんでした。"
      redirect_to users_path
    end
    
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def check_user
    @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/_common.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(63,63) %>
  <table class="table">
    <tbody>
      
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follow</th>
        <th><%= user.followings.count %></th>
      </tr>
      <tr>
        <th>followed</th>
        <th><%= user.followers.count %></th>
      </tr>
      <tr>
        <% if current_user != user %>
          <%= render 'follow/follow', user: user %>
        <% else %>
          <th>
            <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          </th>
        <% end %>      
      </tr>
   </tbody>
  </table>
  <h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label><br>
        <%= f.text_field :title ,class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label><br>
        <%= f.text_area :body ,class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book" ,class: "btn btn-success" %>
      </div>
    <% end %>
</div>

app/views/books/_search.html.erb
<%= form_with url: book_search_path, class: "input-group m-4", local:true do |f| %>
  <%= f.text_field :book_search, class: "form-control input-group-prepend", placeholder: "キーワードを入力" %>
  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <div class="container px-5 px-sm-0">
          <div id="error_explanation">
            <% if @book_one.errors.any? %>
              <h3>
                <% if @book_one.errors.count == 1 %>
                  <%= @book_one.errors.count %> error prohibited this obj from being saved:
                <% else %>
                  <%= @book_one.errors.count %> errors prohibited this obj from being saved:
                <% end %>
              </h3>
              <ul>
                <% @book_one.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        <%= form_with model: @book_one, method: :patch do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title ,class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body ,class: "form-control"  %>
          </div>
          <div class="form-group">
            <%= f.submit "Update Book" ,class: "btn btn-success"%>
          </div>
        <% end %>
        <%= link_to 'Show', book_path %> | <%= link_to 'Back', books_path %>
      </div>
    </div>
  </div>
</main>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/index.html.erb
<p></p>
<div class="container px-5 px-sm-0">
  <div id="error_explanation text-red">
    <% if @book.errors.any? %>
      <h3>
        <% if @book.errors.count == 1 %>
          <%= @book.errors.count %> error prohibited this obj from being saved:
        <% else %>
          <%= @book.errors.count %> errors prohibited this obj from being saved:
        <% end %>
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <%= render 'common', book: @book ,user: current_user %>
    <div class="col-md-8 offset-md-1">
      <%= render "books/search" %>
      <div class="text-danger"><%= flash[:notice] %></div>
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% if @books != nil %>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to image_tag(book.user.get_profile_image(40,40)), user_path(book.user) %></td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
                <%= render 'favorites/favorite_button', book: book %>
                <td>コメント数: <%= book.book_comments.count %></td>
              </tr>
            <% end %>
          <% else %>
            <div class="text-red">検索結果がありません</div>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<p id="notice">
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
</p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'common', book: @book, user: @book_one.user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <a>
                <%= link_to image_tag(@book_one.user.get_profile_image(40,40)), user_path(@book_one.user) %><br>
                <%= link_to @book_one.user.name, user_path(@book_one.user_id) %>
              </a>
            </td>
            <td>
              <%= link_to @book_one.title, book_path(@book_one) %>
            </td>
            <td>
              <%= @book_one.body %>
            </td>
            <% if @book_one.user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path, class: "btn btn-sm btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book_one), method: :delete, class: "btn btn-sm btn-danger ", "data-confirm" => "本当に削除しますか？" %>
              </td>
              <td>
                <%= render 'favorites/favorite_button', book: @book_one %>
              </td>
              <td>
                コメント数: <%= @book_one.book_comments.count %>
              </td>
            <% else %>
              <%= render 'good', book: @book_one %>
              <td>
                コメント数: <%= @book_one.book_comments.count %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div>
        <table>
          <% @book_one.book_comments.each do |book_comment| %>
          <tr>
            <td>
              <%= image_tag book_comment.user.get_profile_image(40,40) %><br>
              <%= link_to book_comment.user.name, user_path(book_comment.user_id) %>
            </td>
            <td>
              <%= book_comment.comment %>
            </td>
            <td>
              <% if book_comment.user == current_user %>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </table>
      </div>
      <div>
        <%= form_with model: [@book_one, @book_comment] do |f| %>
        <div class="form-group">
          <%= f.text_area :comment , class: "form-control" %>
        </div>
        <div>
          <%= f.submit "送信" %>
        </div>
        <% end %>
      </div>
    </div>

app/views/favorites/_favorite_button.html.erb
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, class: "heart" do %>
      <i class="fas fa-heart"></i><%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post do %>
      <i class="fas fa-heart"></i><%= book.favorites.count %>
    <% end %>
  <% end %>
</td>

app/views/follow/_follow.html.erb
<% if current_user.following?(user) %>
<th>
  <%= link_to user_relationships_path(user.id), method: :delete, class: "btn btn-outline-secondary btn-block" do %> 
    unfollow
  <% end %>
</th>
<% else %>
<th>
  <%= link_to user_relationships_path(user.id), method: :post, class: "btn btn-outline-secondary btn-block" do %>
    follow 
  <% end %>
</th>
<% end %>

app/views/homes/about.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/homes/top.html.erb
<main>
  <p id="notice">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <p>have fun to use bookers!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in" ,new_user_session_path ,class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
          </div>
          <div class="row">
            <%= link_to "Sign up" ,new_user_registration_path ,class: 'btn btn-success btn-sm btn-block sign_up' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", "/", class: "navbar-brand" %>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
               <%= link_to users_path, class: "nav-link text-light" do %>
                 <i class="fas fa-users"></i> Users
               <% end %>
              </li>
              <li>
                <%= link_to books_path, class: "nav-link text-light" do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete , class: "nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i> logout
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to root_path ,class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path ,class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path ,class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i> sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i> login
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/relationships/followers.html.erb
<h1>Relationships#followers</h1>
<p>Find me in app/views/relationships/followers.html.erb</p>

app/views/relationships/followings.html.erb
<h1>Relationships#followings</h1>
<p>Find me in app/views/relationships/followings.html.erb</p>

app/views/users/_search.html.erb
<%= form_with url: user_search_path, class: "input-group m-4", local:true do |f| %>
  <%= f.text_field :user_search, class: "form-control input-group-prepend", placeholder: "キーワードを入力" %>
  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <div class="container px-5 px-sm-0">
          <div id="error_explanation">
            <% if @user.errors.any? %>
              <h3>
                <% if @user.errors.count == 1 %>
                  <%= @user.errors.count %> error prohibited this obj from being saved:
                <% else %>
                  <%= @user.errors.count %> errors prohibited this obj from being saved:
                <% end %>
              </h3>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        <%= form_with model: @user do |f| %>
          <div class="form-group">
            <label for="user_name">Name</label><br>
            <%= f.text_field :name, id:"user_name" ,class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="user_image">Image</label><br>
            <%= f.file_field :profile_image, accept:"image/*" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Introduction</label><br>
            <%= f.text_area :introduction, id:"user_introduction" ,class: "form-control" %>
          </div>
          <%= f.submit "Update User" ,class: "btn btn-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
</main>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/index.html.erb
<p></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/common', book: @book , user: current_user %>
    <div class="col-md-8 offset-md-1">
      <%= render 'users/search' %>
      <div class="text-danger"><%= flash[:notice] %></div>
      <h2>Users</h2>
      <table class="table">
        <thread>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thread>
        <tbody>
          <% if @users != nil %>
            <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.get_profile_image(40,40) %></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          <% elsif @users == [] %>
            <div class="text-danger">検索結果としてヒットしたものはありませんでした。</div>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice">
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
</p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/common', book: @book , user: @user %>
    <div class="col-md-8 offset-md-1">
      <%= render "books/search" %>
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(book.user.get_profile_image(40,40)), user_path(book.user) %></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <%= render 'favorites/favorite_button', book: book %>
              <td>コメント数: <%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>